#!/usr/bin/perl
use strict;
use warnings;

use File::Spec;

die "no EMAIL_SENDER_TRANSPORT_SENDMAIL_TEST_LOGDIR"
  unless my $dir = $ENV{EMAIL_SENDER_TRANSPORT_SENDMAIL_TEST_LOGDIR};

my $logfile = File::Spec->catfile($dir, 'sendmail.log');

my $input = join '', <STDIN>;

open my $fh, '>', $logfile
  or die "Cannot write to logfile $logfile: $!";

print $fh "CLI args: @ARGV\n";
if (defined $input && length $input) {
  print $fh "Executed with input on STDIN\n$input";
} else {
  print $fh "Executed with no input on STDIN\n";
}

