#!perl
use strict;
use warnings;

use File::Spec;
use File::Temp;

my $dir = $ENV{EMAIL_SENDER_TRANSPORT_SENDMAIL_TEST_LOGDIR} 
        || File::Temp::tempdir( CLEANUP => 1 );

my $logfile = File::Spec->catfile($dir, 'sendmail.log');

my $input = join '', <STDIN>;

open my $fh, '>', $logfile
  or die "Cannot write to logfile $logfile: $!";

print $fh "CLI args: @ARGV\n";
if (defined $input && length $input) {
  print $fh "Executed with input on STDIN\n$input";
} else {
  print $fh "Executed with no input on STDIN\n";
}

